---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: peopleapi
  namespace: monitoring
spec:
  selector:
    app: peopleapi
  replicas: 1
  template:
    metadata:
      labels:
        app: peopleapi
    spec:
      containers:
        - name: peopleapi
          image: peddadas/testhpa-repo:peopleapi
          ports:
            - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: peopleapi-svc
  namespace: monitoring
labels:
  operated-prometheus: 'true'  
spec:
  selector:
    app: peopleapi
    deploymentconfig: peopleapi
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
      name: web
---
  kind: Route
  apiVersion: v1
  metadata:
    name: peopleapi-route
  spec: 
   host: peopleapi
   port:
    sourcePort: web
    targetPort: web
   tls:
    termination: edge          
    insecureEdgeTerminationPolicy: Redirect
   to:
    kind: Service
    name: peopleapi-svc
    weight: 100
 ---   
